language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
cache: yarn # speeds up yarn installs
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
before_script:
  - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

# # see https://docs.travis-ci.com/user/deployment/heroku/
# deploy:
#   skip_cleanup: true # prevents travis from deleting the build
#   provider: heroku
#   api_key:
#     secure: "YOUR ***ENCRYPTED*** API KEY HERE"
